/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
    edu.princeton.cs.algs4.Draw draw;

    public App() {
        Grade grade = new Grade(10, 10);
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600); //Define o tamanho da janela
        this.draw.setXscale(0, 1000); //Escala em X
        this.draw.setYscale(0, 600); //Escala em Y
        grade.desenhar(draw);
        }
    public static void main(String[] args) {
        App app = new App();
        app.draw.show();

    }
}
